spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/support
spring.datasource.username=support
spring.datasource.password=support
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true  

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

openai.api-key=${OPENAI_API_KEY}